language: python
python:
  - "3.6"

before_install:
  - export DJANGO_SETTINGS_MODULE=dbbackend.settings
  - export PYTHONPATH=$HOME/builds/juliabiro/confabulations_v3
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==1.11 --quiet
  - pip install psycopg2 --quiet

env:
  global:
    - AWS_ACCESS_KEY_ID=AKIAJHVLPF3SDDTOYKXQ
    - AWS_SECRET_ACCESS_KEY=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

script:
  - ./smart_pylint dbbackend/
  - ./smart_pylint confabulation/
  - python manage.py makemigrations
  - python manage.py migrate
  - python manage.py test confabulation/tests
