language: python
python:
  - "3.6"

services: postgresql

before_install:
  - export DJANGO_SETTINGS_MODULE=your_project.settings
  - export PYTHONPATH=$HOME/builds/juliabiro/confabulations_v3
  - export PIP_USE_MIRRORS=true

install:
  - pip install -r requirements.txt
  - pip install django==$DJANGO --quiet
  - pip install psycopg2 --quiet

before_script:
  - psql -c "CREATE DATABASE mydb;" -U postgres

script:
  - python manage.py syncdb --noinput
  - pylint confabulation
