version: '2'
services:
  db:
    image: postgres:latest
    volumes:
      #- ./data/db:/var/lib/postgresql/data
      - ./db_backups:/db_backups
    env_file:
      - ${ENV_FILE}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 3s
      timeout: 30s
      retries: 3
    ports:
      - "5432:5432"
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
      - /Users/juliabiro/Downloads/pk-APKAJ6OXE6IOMB4LF4FA.pem:/pk-cloudfront.pem
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - ${ENV_FILE} 
