#!/bin/sh

pylint $@

pylint_exit_status=$?

# Fail Travis build if Pylint returns fatal (1) | error (2)
if [ $pylint_exit_status -lt 3 ]; then
    echo "Pylint failed"
    exit 1
else
    echo "Pylint passed"
    exit 0
fi
