#!/bin/sh

pylint $@

pylint_exit_status=$?
echo $pylint_exit_status

# Fail Travis build if Pylint returns fatal (1) | error (2)
if [ $(($pylint_exit_status)) -eq 1 ] || [ $(($pylint_exit_status)) -eq 2 ]; then
    echo "Pylint failed"
    exit 1
else
    echo "Pylint passed"
    exit 0
fi
