"""
Django settings for dbbackend project.

Generated by 'django-admin startproject' using Django 1.10.6.

For more information on this file, see
https://docs.djangoproject.com/en/1.10/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.10/ref/settings/
"""

import os
import dj_database_url

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PROJECT_ROOT = os.path.dirname(os.path.abspath(__file__))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.10/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if 'DJANGO_SECRET_KEY' in os.environ:
    SECRET_KEY = os.environ['DJANGO_SECRET_KEY']
else:
    SECRET_KEY="alma"

# SECURITY WARNING: don't run with debug turned on in production!
if 'LOCAL' in os.environ:
    DEBUG= True
else:
    DEBUG = False

CLOUDINARY_API_KEY=""
CLOUDINARY_API_SECRET=""
if 'CLOUDINARY_API_KEY' in os.environ:
    CLOUDINARY_API_KEY=os.environ['CLOUDINARY_API_KEY']
if 'CLOUDINARY_API_SECRET' in os.environ:
    CLOUDINARY_API_SECRET=os.environ['CLOUDINARY_API_SECRET']


CLOUDFRONT_KEY_ID=""
if "CLOUDFRONT_KEY_ID" in os.environ:
    CLOUDFRONT_KEY_ID=os.environ["CLOUDFRONT_KEY_ID"]

HONEYCOMB_API_KEY=""
if "HONEYCOMB_API_KEY" in os.environ:
    HONEYCOMB_API_KEY=os.environ["HONEYCOMB_API_KEY"]

ALLOWED_HOSTS = []

SITE_NAME = "Beyond The Photograph"
DEBUG_SITE_NAME = "LOCAL DB"

# Application definition

INSTALLED_APPS = [
    'confabulation.apps.ConfabulationConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'colorful',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'beeline.middleware.django.HoneyMiddleware',
]

ROOT_URLCONF = 'dbbackend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
            'libraries' : {
                'staticfiles': 'django.templatetags.static', 
            }
        },
    },
]

WSGI_APPLICATION = 'dbbackend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.10/ref/settings/#databases
db_from_env = dj_database_url.config()
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'postgres',
        'USER': 'postgres',
        'HOST': 'db',
        'PASSWORD': 'postgres',
        'PORT': 5432,
    }
}

if "DATABASE_URL" in os.environ:
    DATABASES['default'].update(db_from_env)


# Password validation
# https://docs.djangoproject.com/en/1.10/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.10/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Honor the 'X-Forwarded-Proto' header for request.is_secure()
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')

# Allow all host headers
ALLOWED_HOSTS = ['confabulations-v3.herokuapp.com', 'localhost', 'archival-test.herokuapp.com']
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.10/howto/static-files/

STATIC_ROOT = os.path.join(PROJECT_ROOT, 'staticfiles')
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'confabulation/staticfiles/')
]


LOGIN_URL = '/login/'
LOGIN_REDIRECT_URL = '/confabulation/'


# test database for travisci
if 'TRAVIS' in os.environ:
    DATABASES = {
        'default': {
            'ENGINE':   'django.db.backends.postgresql',
            'NAME':     'travis_ci_test',
            'USER': 'postgres',
            'HOST': 'localhost',
            'PASSWORD': 'postgres',
            'PORT': 5432,
        }
    }

