# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 20:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('name', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('profile', models.CharField(max_length=2000)),
                ('participation_group', models.CharField(choices=[(b'2', b'non_photographer'), (b'1', b'photographer'), (b'0', b'student')], max_length=1)),
                ('gender', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('file', models.FilePathField()),
                ('duration', models.DurationField()),
                ('order_in_recording', models.IntegerField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Recording',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('data_collection_circumstances', models.CharField(max_length=2000)),
                ('sound_recording', models.FilePathField()),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confabulation.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transscribe_eng', models.CharField(max_length=10000)),
                ('transscribe_hu', models.CharField(max_length=10000)),
                ('video_url', models.FilePathField()),
                ('thumbnail', models.FilePathField()),
                ('analysis_points', models.CharField(choices=[(b'0', b'confabulation'), (b'1', b'connection'), (b'3', b'emotion'), (b'4', b'framing'), (b'2', b'interaction')], max_length=1)),
                ('emotions', models.CharField(choices=[(b'1', b'conflicted'), (b'3', b'surprised'), (b'0', b'trauma')], max_length=1)),
                ('interactions', models.CharField(choices=[(b'1', b'analyze'), (b'4', b'audience'), (b'0', b'block'), (b'2', b'non_block_trigger'), (b'3', b'respond_to_trigger')], max_length=1)),
                ('framing', models.CharField(choices=[(b'1', b'connection'), (b'0', b'gray_matter'), (b'2', b'theme'), (b'4', b'themeSubject'), (b'3', b'themeconnection')], max_length=1)),
                ('connections', models.CharField(choices=[(b'0', b'story_to_story'), (b'1', b'theme'), (b'3', b'theme_subject'), (b'2', b'theme_to_theme')], max_length=1)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confabulation.Photo')),
            ],
        ),
        migrations.CreateModel(
            name='StoryConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ManyToManyField(to='confabulation.Story')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('photos', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confabulation.Story')),
            ],
        ),
        migrations.CreateModel(
            name='ThemeConnection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('story', models.ManyToManyField(to='confabulation.Theme')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='themes',
            field=models.ManyToManyField(to='confabulation.Theme'),
        ),
        migrations.AddField(
            model_name='recording',
            name='stories',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='confabulation.Story'),
        ),
        migrations.AddField(
            model_name='participant',
            name='recording',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='confabulation.Recording'),
        ),
    ]
