# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispoint',
            name='name',
            field=models.CharField(default='alma', max_length=50),
            preserve_default=False,
        ),
    ]
