# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 18:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0002_remove_story_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='profile',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='analysis',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.AnalysisPoint'),
        ),
        migrations.AlterField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Photo'),
        ),
    ]
