# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-27 13:45
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0002_auto_20170326_2039'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='duration',
            field=models.DurationField(blank=True, default=datetime.timedelta, null=True),
        ),
    ]
