# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0002_analysispoint_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='chain',
            name='name',
            field=models.CharField(default='alma', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='theme',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default='korte', max_length=50),
            preserve_default=False,
        ),
    ]
