# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0003_auto_20170326_1327'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recording',
            old_name='sound_recording',
            new_name='sound_recording_url',
        ),
    ]
