# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-28 20:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0003_story_duration'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='analysispoint',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysispoint',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='analysistype',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='chain',
            name='connection_range',
            field=models.TextField(choices=[(b'Interconnection', b'interconnection'), (b'Intraconnection', b'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='chain',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='chain',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='participant',
            name='gender',
            field=models.TextField(choices=[(b'female', b'female'), (b'male', b'male'), (b'other', b'other')], max_length=20),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.TextField(max_length=200),
        ),
        migrations.AlterField(
            model_name='participant',
            name='participation_group',
            field=models.TextField(choices=[(b'non-photgrapher', b'non_photographer'), (b'photographer', b'photographer'), (b'student', b'student')], max_length=50),
        ),
        migrations.AlterField(
            model_name='photo',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='recording',
            name='data_collection_circumstances',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='recording',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='name',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='story',
            name='notes',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='storytostoryconnection',
            name='connection_range',
            field=models.TextField(choices=[(b'Interconnection', b'interconnection'), (b'Intraconnection', b'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='connection_range',
            field=models.TextField(choices=[(b'Interconnection', b'interconnection'), (b'Intraconnection', b'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='theme',
            name='name',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='transscription',
            name='text_eng',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='transscription',
            name='text_hu',
            field=models.TextField(default=''),
        ),
    ]
