# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 14:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0004_auto_20170326_1332'),
    ]

    operations = [
        migrations.CreateModel(
            name='Analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Emotion',
            fields=[
                ('analysispoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='confabulation.AnalysisPoint')),
                ('type', models.CharField(blank=True, choices=[(b'Conflicted', b'conflicted'), (b'Emotional', b'emotional'), (b'Traumatic', b'traumatic')], max_length=20, null=True)),
            ],
            bases=('confabulation.analysispoint',),
        ),
        migrations.RemoveField(
            model_name='emotions',
            name='analysispoint_ptr',
        ),
        migrations.RenameField(
            model_name='story',
            old_name='analysis_points',
            new_name='analysis',
        ),
        migrations.RemoveField(
            model_name='audience',
            name='types',
        ),
        migrations.RemoveField(
            model_name='framing',
            name='types',
        ),
        migrations.AddField(
            model_name='analysispoint',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='audience',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Negative', b'negative'), (b'Positive', b'positive')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='framing',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Gray Matter', b'gray_matter'), (b'Identification', b'identification'), (b'Not sure it is true', b'not_sure_it_is_true')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='confabulation',
            name='type',
            field=models.CharField(blank=True, choices=[(b'Confabulation', b'confabulation'), (b'Partial Confabulation', b'partial_confabulation')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='interaction',
            name='type',
            field=models.CharField(blank=True, choices=[(b'analyze', b'analyze'), (b'blocks', b'block'), (b'Not respond to trigger question', b'not_respond_to_trigger'), (b'Respond to trigger question', b'respond_to_trigger')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Emotions',
        ),
        migrations.AddField(
            model_name='analysis',
            name='audience',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Audience'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='confabulations',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Confabulation'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='emotions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Emotion'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='framing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Framing'),
        ),
        migrations.AddField(
            model_name='analysis',
            name='interactions',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Interaction'),
        ),
    ]
