# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 19:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0004_story_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='transscription',
            name='recording',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Recording'),
            preserve_default=False,
        ),
    ]
