# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0005_auto_20170326_1405'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='analysis',
        ),
        migrations.AddField(
            model_name='story',
            name='analysis',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.AnalysisPoint'),
        ),
    ]
