# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 14:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0006_auto_20170326_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='recording',
            name='transscription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Transscription'),
        ),
        migrations.RemoveField(
            model_name='story',
            name='photos',
        ),
        migrations.AddField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Photo'),
        ),
    ]
