# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-25 17:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0006_auto_20170328_2034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='story',
            options={'ordering': ['-name'], 'verbose_name_plural': 'Stories'},
        ),
        migrations.AlterField(
            model_name='story',
            name='order_in_recording',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
