# Generated by Django 2.0.2 on 2018-03-05 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0008_auto_20180305_0722'),
    ]

    operations = [
        migrations.RenameField(
            model_name='keyword',
            old_name='keyword',
            new_name='name',
        ),
    ]
