# Generated by Django 2.0.2 on 2018-03-05 12:19

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0008_auto_20180123_1902'),
    ]

    operations = [
    ]
