# Generated by Django 2.0.2 on 2018-03-05 13:28

import colorful.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0008_auto_20180123_1902'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('color_code', colorful.fields.RGBColorField()),
            ],
        ),
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='confabulation.Keyword'),
        ),
        migrations.AddField(
            model_name='story',
            name='era',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Era'),
        ),
    ]
