# Generated by Django 2.0.2 on 2018-03-05 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0009_auto_20180305_0729'),
        ('confabulation', '0008_auto_20180123_1902'),
    ]

    operations = [
    ]
