# Generated by Django 2.0.2 on 2018-03-06 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0009_keyword'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='confabulation.Keyword'),
        ),
    ]
