# Generated by Django 2.0.2 on 2018-03-05 19:22

import colorful.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0010_auto_20180305_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Era',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('color_code', colorful.fields.RGBColorField()),
            ],
        ),
        migrations.RemoveField(
            model_name='story',
            name='keywords',
        ),
        migrations.AddField(
            model_name='story',
            name='era',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Era'),
        ),
    ]
