# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-09 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0010_story_keywords'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='file_path',
        ),
    ]
