# Generated by Django 2.0.2 on 2018-03-05 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0011_auto_20180305_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='keywords',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
