# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0011_auto_20170326_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='analysis',
            field=models.ManyToManyField(to='confabulation.AnalysisPoint'),
        ),
    ]
