# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-11-05 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0011_remove_photo_file_path'),
    ]

    operations = [
        migrations.AddField(
            model_name='analysispoint',
            name='order_in_menu',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='story',
            name='era',
            field=models.ManyToManyField(blank=True, to='confabulation.Era'),
        ),
    ]
