# Generated by Django 2.0.2 on 2018-03-05 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0012_auto_20180305_1931'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.Keyword'),
        ),
    ]
