# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0012_auto_20170326_1504'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='story',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Story'),
            preserve_default=False,
        ),
    ]
