# Generated by Django 2.1.3 on 2018-12-02 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0013_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='connection',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
