# Generated by Django 2.0.2 on 2018-03-05 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0013_auto_20180305_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='analysis',
            field=models.ManyToManyField(blank=True, to='confabulation.AnalysisPoint'),
        ),
        migrations.AlterField(
            model_name='story',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='confabulation.Keyword'),
        ),
        migrations.AlterField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(blank=True, to='confabulation.Photo'),
        ),
    ]
