# Generated by Django 2.0.2 on 2018-03-05 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0014_auto_20180305_1940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='keywords',
        ),
        migrations.AddField(
            model_name='story',
            name='keyworrds',
            field=models.ManyToManyField(blank=True, to='confabulation.Keyword'),
        ),
    ]
