# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-26 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0015_auto_20170326_1509'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='story',
        ),
        migrations.AddField(
            model_name='story',
            name='photos',
            field=models.ManyToManyField(to='confabulation.Photo'),
        ),
        migrations.AlterField(
            model_name='story',
            name='analysis',
            field=models.ManyToManyField(blank=True, null=True, to='confabulation.AnalysisPoint'),
        ),
        migrations.AlterField(
            model_name='transscription',
            name='recording',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='confabulation.Recording'),
        ),
    ]
