# Generated by Django 2.2 on 2019-04-19 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0015_auto_20190419_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chain',
            name='connection_range',
            field=models.CharField(choices=[('Interconnection', 'interconnection'), ('Intraconnection', 'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='connection',
            name='connection_range',
            field=models.CharField(choices=[('Interconnection', 'interconnection'), ('Intraconnection', 'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='storytostoryconnection',
            name='connection_range',
            field=models.CharField(choices=[('Interconnection', 'interconnection'), ('Intraconnection', 'intraconnection')], max_length=30),
        ),
        migrations.AlterField(
            model_name='theme',
            name='connection_range',
            field=models.CharField(choices=[('Interconnection', 'interconnection'), ('Intraconnection', 'intraconnection')], max_length=30),
        ),
    ]
