# Generated by Django 2.0.2 on 2018-03-06 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0016_auto_20180305_1951'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Keywords',
        ),
        migrations.RemoveField(
            model_name='story',
            name='keyworrds',
        ),
        migrations.DeleteModel(
            name='Keyword',
        ),
    ]
