# Generated by Django 2.0.2 on 2018-03-06 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confabulation', '0017_auto_20180306_2058'),
    ]

    operations = [
        migrations.CreateModel(
            name='Keyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='story',
            name='keywords',
            field=models.ManyToManyField(blank=True, to='confabulation.Keyword'),
        ),
    ]
